UPDATE candidatos SET url_imagen='images/opciones-de-voto/cesar-augusto-ortiz-zorro.png' WHERE id_candidato=1;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/luis-alexis-garcia-barrera.png' WHERE id_candidato=2;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/hector-manuel-balaguera-quintana.png' WHERE id_candidato=3;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/jacobo-rivera-gomez.png' WHERE id_candidato=4;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/alba-rocio-romero-garcia.png' WHERE id_candidato=5;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/joel-olmos-cordero.png' WHERE id_candidato=6;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/rubiela-benitex-enriquez.png' WHERE id_candidato=7;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/guillermo-alexander-velandia-granados.png' WHERE id_candidato=8;
UPDATE candidatos SET url_imagen='images/opciones-de-voto/marisela-duarte-rodriguez.png' WHERE id_candidato=9;